include: package:flutter_lints/flutter.yaml


linter:
  rules:
    unnecessary_overrides: false
    avoid_print: false
    empty_catches: false
    prefer_typing_uninitialized_variables: false
    file_names: false
    invalid_return_type_for_catch_error: false
    no_logic_in_create_state: false
    nullable_type_in_catch_clause: false