name: spalhe
description: A new Flutter project.
publish_to: "none"
version: 3.4.5+37

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  google_fonts: ^2.2.0
  get_storage: ^2.0.3
  graphql: ^5.1.1
  dio: ^4.0.4
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_feather_icons: ^2.0.0+1
  mask_text_input_formatter: ^2.1.0
  flutter_svg: ^1.1.0
  simple_moment: ^1.1.1
  validatorless: ^1.2.3
  get: ^4.6.5
  photo_view: ^0.14.0
  hashtagable: ^2.1.0
  google_place: ^0.4.7
  skeletons: ^0.0.3
  in_app_purchase: ^3.0.8
  onesignal_flutter: ^3.4.2
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
