name: spalhe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  google_fonts: ^2.2.0
  get: ^4.6.1
  camera: ^0.9.4+6
  get_storage: ^2.0.3
  dio: ^4.0.4
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  screenshot: ^1.2.3
  video_player: ^2.2.14
  cached_network_image: ^3.2.0
  flutter_feather_icons: ^2.0.0+1
  hashtagable: ^2.0.2+1
  flutter_svg: ^1.0.3
  flutter_staggered_grid_view: ^0.6.0
  salomon_bottom_bar: ^3.2.0
  simple_moment: ^1.1.1
  carousel_slider: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
